version: "3.7"
services:
    php73:
        build:
            context: ./dockerfiles
            dockerfile: dockerfile-php73
        container_name: php73
        ports:
            - 0.0.0.0:9073:9000
        volumes:
            - './htdocs:/usr/share/nginx/html:rw'
            - './hosts:/etc/hosts:rw'
        networks:
            docker_network:
                ipv4_address: 172.16.230.11
    nginx:
        build:
            context: ./dockerfiles
            dockerfile: dockerfile-nginx
        container_name: nginx
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443
        volumes:
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf:rw'
            - './nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:rw'
            - './nginx/mime.types:/etc/nginx/mime.types:rw'
            - './nginx/nginx.conf:/etc/nginx/nginx.conf:rw'
            - './nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf:rw'
            - './htdocs:/usr/share/nginx/html:rw'
            - './hosts:/etc/hosts:rw'
        networks:
            docker_network:
                ipv4_address: 172.16.230.10
    mysql:
        build:
            context: ./dockerfiles
            dockerfile: dockerfile-mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'root'
            MYSQL_PASS: 'root123'
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
          docker_network:
              ipv4_address: 172.16.230.12
networks:
    docker_network:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: 'false'
        ipam:
            driver: default
            config: 
                - subnet: 172.16.230.0/24